count = 9

kek = [['abaddon', 'alchemist', 'axe', 'bounty_hunter', 'chaos_knight', 'crystal_maiden', 'disruptor', 'lich',
        'ogre_magi'],
       ['abaddon', 'alchemist', 'axe', 'bounty_hunter', 'chaos_knight', 'disruptor', 'keeper_of_the_light', 'lich',
        'ogre_magi'],
       ['abaddon', 'alchemist', 'axe', 'bounty_hunter', 'chaos_knight', 'disruptor', 'lich', 'lina', 'ogre_magi'],
       ['abaddon', 'alchemist', 'axe', 'bounty_hunter', 'disruptor', 'doom', 'dragon_knight', 'enchantress',
        'lone_druid'],
       ['abaddon', 'alchemist', 'axe', 'chaos_knight', 'clockwerk', 'crystal_maiden', 'disruptor', 'lich', 'ogre_magi'],
       ['abaddon', 'alchemist', 'axe', 'chaos_knight', 'clockwerk', 'disruptor', 'keeper_of_the_light', 'lich',
        'ogre_magi'],
       ['abaddon', 'alchemist', 'axe', 'chaos_knight', 'clockwerk', 'disruptor', 'lich', 'lina', 'ogre_magi'],
       ['abaddon', 'alchemist', 'axe', 'clockwerk', 'disruptor', 'doom', 'dragon_knight', 'drow_ranger', 'gyrocopter'],
       ['abaddon', 'alchemist', 'axe', 'clockwerk', 'disruptor', 'doom', 'dragon_knight', 'enchantress', 'lone_druid'],
       ['abaddon', 'alchemist', 'axe', 'clockwerk', 'disruptor', 'doom', 'dragon_knight', 'gyrocopter', 'lich'],
       ['abaddon', 'alchemist', 'axe', 'clockwerk', 'disruptor', 'doom', 'dragon_knight', 'gyrocopter', 'necrophos'],
       ['abaddon', 'alchemist', 'axe', 'disruptor', 'doom', 'dragon_knight', 'drow_ranger', 'enchantress',
        'lone_druid'],
       ['abaddon', 'alchemist', 'axe', 'disruptor', 'doom', 'dragon_knight', 'enchantress', 'lich', 'lone_druid'],
       ['abaddon', 'alchemist', 'axe', 'disruptor', 'doom', 'dragon_knight', 'enchantress', 'lone_druid', 'necrophos'],
       ['abaddon', 'alchemist', 'beastmaster', 'bounty_hunter', 'chaos_knight', 'disruptor', 'drow_ranger',
        'enchantress', 'lycan'],
       ['abaddon', 'alchemist', 'beastmaster', 'bounty_hunter', 'chaos_knight', 'disruptor', 'drow_ranger',
        'lone_druid', 'lycan'],
       ['abaddon', 'alchemist', 'beastmaster', 'chaos_knight', 'clockwerk', 'disruptor', 'drow_ranger', 'enchantress',
        'lycan'],
       ['abaddon', 'alchemist', 'beastmaster', 'chaos_knight', 'clockwerk', 'disruptor', 'drow_ranger', 'gyrocopter',
        'lycan'],
       ['abaddon', 'alchemist', 'beastmaster', 'chaos_knight', 'clockwerk', 'disruptor', 'drow_ranger', 'lone_druid',
        'lycan'],
       ['abaddon', 'alchemist', 'beastmaster', 'chaos_knight', 'disruptor', 'drow_ranger', 'enchantress', 'furion',
        'lycan'],
       ['abaddon', 'alchemist', 'beastmaster', 'chaos_knight', 'disruptor', 'drow_ranger', 'enchantress', 'lone_druid',
        'lycan'],
       ['abaddon', 'alchemist', 'beastmaster', 'chaos_knight', 'disruptor', 'drow_ranger', 'furion', 'lone_druid',
        'lycan'],
       ['abaddon', 'axe', 'bat_rider', 'beastmaster', 'doom', 'drow_ranger', 'enchantress', 'furion', 'lycan'],
       ['abaddon', 'axe', 'bat_rider', 'beastmaster', 'doom', 'drow_ranger', 'enchantress', 'lone_druid', 'lycan'],
       ['abaddon', 'axe', 'bat_rider', 'beastmaster', 'doom', 'drow_ranger', 'furion', 'lone_druid', 'lycan'],
       ['abaddon', 'axe', 'beastmaster', 'chaos_knight', 'crystal_maiden', 'enchantress', 'lich', 'lone_druid',
        'ogre_magi'],
       ['abaddon', 'axe', 'beastmaster', 'chaos_knight', 'doom', 'drow_ranger', 'enchantress', 'furion', 'lycan'],
       ['abaddon', 'axe', 'beastmaster', 'chaos_knight', 'doom', 'drow_ranger', 'enchantress', 'lone_druid', 'lycan'],
       ['abaddon', 'axe', 'beastmaster', 'chaos_knight', 'doom', 'drow_ranger', 'furion', 'lone_druid', 'lycan'],
       ['abaddon', 'axe', 'beastmaster', 'chaos_knight', 'drow_ranger', 'enchantress', 'enigma', 'furion', 'lycan'],
       ['abaddon', 'axe', 'beastmaster', 'chaos_knight', 'drow_ranger', 'enchantress', 'furion', 'lycan', 'ogre_magi'],
       ['abaddon', 'axe', 'beastmaster', 'chaos_knight', 'drow_ranger', 'enchantress', 'lone_druid', 'lycan',
        'ogre_magi'],
       ['abaddon', 'axe', 'beastmaster', 'chaos_knight', 'drow_ranger', 'enigma', 'furion', 'lone_druid', 'lycan'],
       ['abaddon', 'axe', 'beastmaster', 'chaos_knight', 'drow_ranger', 'furion', 'lone_druid', 'lycan', 'ogre_magi'],
       ['abaddon', 'axe', 'beastmaster', 'chaos_knight', 'enchantress', 'keeper_of_the_light', 'lich', 'lone_druid',
        'ogre_magi'],
       ['abaddon', 'axe', 'beastmaster', 'chaos_knight', 'enchantress', 'lich', 'lina', 'lone_druid', 'ogre_magi'],
       ['abaddon', 'axe', 'beastmaster', 'doom', 'dragon_knight', 'drow_ranger', 'enchantress', 'furion', 'lycan'],
       ['abaddon', 'axe', 'beastmaster', 'doom', 'dragon_knight', 'drow_ranger', 'enchantress', 'lone_druid', 'lycan'],
       ['abaddon', 'axe', 'beastmaster', 'doom', 'dragon_knight', 'drow_ranger', 'enchantress', 'lone_druid', 'medusa'],
       ['abaddon', 'axe', 'beastmaster', 'doom', 'dragon_knight', 'drow_ranger', 'furion', 'lone_druid', 'lycan'],
       ['abaddon', 'axe', 'beastmaster', 'doom', 'drow_ranger', 'enchantress', 'enigma', 'furion', 'lycan'],
       ['abaddon', 'axe', 'beastmaster', 'doom', 'drow_ranger', 'enchantress', 'furion', 'luna', 'lycan'],
       ['abaddon', 'axe', 'beastmaster', 'doom', 'drow_ranger', 'enchantress', 'lone_druid', 'luna', 'lycan'],
       ['abaddon', 'axe', 'beastmaster', 'doom', 'drow_ranger', 'enigma', 'furion', 'lone_druid', 'lycan'],
       ['abaddon', 'axe', 'beastmaster', 'doom', 'drow_ranger', 'furion', 'lone_druid', 'luna', 'lycan'],
       ['abaddon', 'axe', 'chaos_knight', 'crystal_maiden', 'disruptor', 'enchantress', 'lich', 'lone_druid',
        'ogre_magi'],
       ['abaddon', 'axe', 'chaos_knight', 'crystal_maiden', 'enchantress', 'juggernaut', 'lich', 'lone_druid',
        'ogre_magi'],
       ['abaddon', 'axe', 'chaos_knight', 'disruptor', 'enchantress', 'keeper_of_the_light', 'lich', 'lone_druid',
        'ogre_magi'],
       ['abaddon', 'axe', 'chaos_knight', 'disruptor', 'enchantress', 'lich', 'lina', 'lone_druid', 'ogre_magi'],
       ['abaddon', 'axe', 'chaos_knight', 'enchantress', 'juggernaut', 'keeper_of_the_light', 'lich', 'lone_druid',
        'ogre_magi'],
       ['abaddon', 'axe', 'chaos_knight', 'enchantress', 'juggernaut', 'lich', 'lina', 'lone_druid', 'ogre_magi'],
       ['abaddon', 'beastmaster', 'chaos_knight', 'disruptor', 'drow_ranger', 'enchantress', 'enigma', 'furion',
        'lycan'],
       ['abaddon', 'beastmaster', 'chaos_knight', 'disruptor', 'drow_ranger', 'enigma', 'furion', 'lone_druid',
        'lycan'],
       ['abaddon', 'beastmaster', 'chaos_knight', 'drow_ranger', 'enchantress', 'enigma', 'furion', 'juggernaut',
        'lycan'], ['abaddon', 'beastmaster', 'chaos_knight', 'drow_ranger', 'enchantress', 'enigma', 'furion', 'lycan',
                   'morphling'],
       ['abaddon', 'beastmaster', 'chaos_knight', 'drow_ranger', 'enigma', 'furion', 'juggernaut', 'lone_druid',
        'lycan'], ['abaddon', 'beastmaster', 'chaos_knight', 'drow_ranger', 'enigma', 'furion', 'lone_druid', 'lycan',
                   'morphling'],
       ['abaddon', 'chaos_knight', 'crystal_maiden', 'enchantress', 'enigma', 'furion', 'lich', 'lone_druid',
        'morphling'],
       ['abaddon', 'chaos_knight', 'crystal_maiden', 'enchantress', 'enigma', 'furion', 'lich', 'lycan', 'morphling'],
       ['abaddon', 'chaos_knight', 'crystal_maiden', 'enigma', 'furion', 'lich', 'lone_druid', 'lycan', 'morphling'],
       ['abaddon', 'chaos_knight', 'drow_ranger', 'enchantress', 'enigma', 'furion', 'lycan', 'medusa', 'morphling'],
       ['abaddon', 'chaos_knight', 'drow_ranger', 'enigma', 'furion', 'lone_druid', 'lycan', 'medusa', 'morphling'],
       ['abaddon', 'chaos_knight', 'enchantress', 'enigma', 'furion', 'keeper_of_the_light', 'lich', 'lone_druid',
        'morphling'],
       ['abaddon', 'chaos_knight', 'enchantress', 'enigma', 'furion', 'keeper_of_the_light', 'lich', 'lycan',
        'morphling'],
       ['abaddon', 'chaos_knight', 'enchantress', 'enigma', 'furion', 'lich', 'lina', 'lone_druid', 'morphling'],
       ['abaddon', 'chaos_knight', 'enchantress', 'enigma', 'furion', 'lich', 'lina', 'lycan', 'morphling'],
       ['abaddon', 'chaos_knight', 'enchantress', 'enigma', 'furion', 'lich', 'lycan', 'morphling', 'ogre_magi'],
       ['abaddon', 'chaos_knight', 'enigma', 'furion', 'keeper_of_the_light', 'lich', 'lone_druid', 'lycan',
        'morphling'],
       ['abaddon', 'chaos_knight', 'enigma', 'furion', 'lich', 'lina', 'lone_druid', 'lycan', 'morphling'],
       ['abaddon', 'chaos_knight', 'enigma', 'furion', 'lich', 'lone_druid', 'lycan', 'morphling', 'ogre_magi'],
       ['abaddon', 'doom', 'dragon_knight', 'enchantress', 'enigma', 'furion', 'lich', 'morphling', 'ogre_magi'],
       ['abaddon', 'doom', 'dragon_knight', 'enchantress', 'enigma', 'lich', 'lone_druid', 'morphling', 'ogre_magi'],
       ['abaddon', 'doom', 'dragon_knight', 'enigma', 'furion', 'lich', 'lone_druid', 'morphling', 'ogre_magi'],
       ['abaddon', 'doom', 'enchantress', 'enigma', 'furion', 'lich', 'lycan', 'morphling', 'ogre_magi'],
       ['abaddon', 'doom', 'enigma', 'furion', 'lich', 'lone_druid', 'lycan', 'morphling', 'ogre_magi'],
       ['alchemist', 'axe', 'bat_rider', 'bounty_hunter', 'disruptor', 'doom', 'dragon_knight', 'enchantress',
        'lone_druid'],
       ['alchemist', 'axe', 'bat_rider', 'clockwerk', 'disruptor', 'doom', 'dragon_knight', 'enchantress',
        'lone_druid'],
       ['alchemist', 'axe', 'bounty_hunter', 'chaos_knight', 'disruptor', 'doom', 'dragon_knight', 'enchantress',
        'lone_druid'],
       ['alchemist', 'axe', 'bounty_hunter', 'chaos_knight', 'disruptor', 'dragon_knight', 'enchantress', 'lone_druid',
        'ogre_magi'],
       ['alchemist', 'axe', 'bounty_hunter', 'disruptor', 'doom', 'dragon_knight', 'enchantress', 'lone_druid', 'luna'],
       ['alchemist', 'axe', 'bounty_hunter', 'disruptor', 'doom', 'enchantress', 'enigma', 'furion', 'lycan'],
       ['alchemist', 'axe', 'bounty_hunter', 'disruptor', 'doom', 'enigma', 'furion', 'lone_druid', 'lycan'],
       ['alchemist', 'axe', 'chaos_knight', 'clockwerk', 'disruptor', 'doom', 'dragon_knight', 'enchantress',
        'lone_druid'],
       ['alchemist', 'axe', 'chaos_knight', 'clockwerk', 'disruptor', 'dragon_knight', 'enchantress', 'gyrocopter',
        'lone_druid'],
       ['alchemist', 'axe', 'chaos_knight', 'clockwerk', 'disruptor', 'dragon_knight', 'enchantress', 'lone_druid',
        'ogre_magi'],
       ['alchemist', 'axe', 'clockwerk', 'crystal_maiden', 'disruptor', 'doom', 'enchantress', 'gyrocopter',
        'lone_druid'],
       ['alchemist', 'axe', 'clockwerk', 'disruptor', 'doom', 'dragon_knight', 'enchantress', 'gyrocopter',
        'lone_druid'],
       ['alchemist', 'axe', 'clockwerk', 'disruptor', 'doom', 'dragon_knight', 'enchantress', 'lone_druid', 'luna'],
       ['alchemist', 'axe', 'clockwerk', 'disruptor', 'doom', 'enchantress', 'enigma', 'furion', 'lycan'],
       ['alchemist', 'axe', 'clockwerk', 'disruptor', 'doom', 'enchantress', 'furion', 'gyrocopter', 'lycan'],
       ['alchemist', 'axe', 'clockwerk', 'disruptor', 'doom', 'enchantress', 'gyrocopter', 'keeper_of_the_light',
        'lone_druid'],
       ['alchemist', 'axe', 'clockwerk', 'disruptor', 'doom', 'enchantress', 'gyrocopter', 'kunkka', 'lone_druid'],
       ['alchemist', 'axe', 'clockwerk', 'disruptor', 'doom', 'enchantress', 'gyrocopter', 'lina', 'lone_druid'],
       ['alchemist', 'axe', 'clockwerk', 'disruptor', 'doom', 'enchantress', 'gyrocopter', 'lone_druid', 'lycan'],
       ['alchemist', 'axe', 'clockwerk', 'disruptor', 'doom', 'enigma', 'furion', 'lone_druid', 'lycan'],
       ['alchemist', 'axe', 'clockwerk', 'disruptor', 'doom', 'furion', 'gyrocopter', 'lone_druid', 'lycan'],
       ['alchemist', 'axe', 'disruptor', 'doom', 'enchantress', 'enigma', 'furion', 'lycan', 'morphling'],
       ['alchemist', 'axe', 'disruptor', 'doom', 'enigma', 'furion', 'lone_druid', 'lycan', 'morphling'],
       ['alchemist', 'beastmaster', 'chaos_knight', 'clockwerk', 'disruptor', 'dragon_knight', 'enchantress',
        'gyrocopter', 'lone_druid'],
       ['alchemist', 'chaos_knight', 'clockwerk', 'disruptor', 'dragon_knight', 'enchantress', 'gyrocopter',
        'juggernaut', 'lone_druid'],
       ['axe', 'beastmaster', 'doom', 'drow_ranger', 'enchantress', 'enigma', 'furion', 'lich', 'lycan'],
       ['axe', 'beastmaster', 'doom', 'drow_ranger', 'enchantress', 'enigma', 'furion', 'lycan', 'morphling'],
       ['axe', 'beastmaster', 'doom', 'drow_ranger', 'enchantress', 'enigma', 'furion', 'lycan', 'necrophos'],
       ['axe', 'beastmaster', 'doom', 'drow_ranger', 'enigma', 'furion', 'lich', 'lone_druid', 'lycan'],
       ['axe', 'beastmaster', 'doom', 'drow_ranger', 'enigma', 'furion', 'lone_druid', 'lycan', 'morphling'],
       ['axe', 'beastmaster', 'doom', 'drow_ranger', 'enigma', 'furion', 'lone_druid', 'lycan', 'necrophos'],
       ['axe', 'beastmaster', 'doom', 'enchantress', 'enigma', 'furion', 'lycan', 'medusa', 'morphling'],
       ['axe', 'beastmaster', 'doom', 'enigma', 'furion', 'lone_druid', 'lycan', 'medusa', 'morphling'],
       ['doom', 'drow_ranger', 'enchantress', 'enigma', 'furion', 'lich', 'lycan', 'morphling', 'ogre_magi'],
       ['doom', 'drow_ranger', 'enigma', 'furion', 'lich', 'lone_druid', 'lycan', 'morphling', 'ogre_magi'],
       ['doom', 'enchantress', 'enigma', 'furion', 'lich', 'lycan', 'morphling', 'necrophos', 'ogre_magi'],
       ['doom', 'enigma', 'furion', 'lich', 'lone_druid', 'lycan', 'morphling', 'necrophos', 'ogre_magi']]
